In [2]:
import pandas as pd

In [3]:
a = [3, 4, 78, 6]
b = [43, 42, 178, 76]
c = [38, 45, 728, 46]

In [4]:
arla = pd.DataFrame({"a": a,
                    "b": b,
                   "c": c})

In [5]:
type(arla)

pandas.DataFrame

In [6]:
arla

    a    b    c
0   3   43   38
1   4   42   45
2  78  178  728
3   6   76   46

In [7]:
arla['a']

0     3
1     4
2    78
3     6
Name: a, dtype: int64

In [8]:
d = arla ['a']

In [9]:
type(d)

pandas.Series

In [10]:
e = list (d)

In [11]:
e

[3, 4, 78, 6]

In [12]:
a == e

True

In [15]:
arla["row_mean"] = arla.mean(axis=1)

In [16]:
arla

    a    b    c    row_mean
0   3   43   38   28.000000
1   4   42   45   30.333333
2  78  178  728  328.000000
3   6   76   46   42.666667

In [19]:
df = pd.read_csv('/work/ExpPsyLing/Stroop-raw-over-the-years.csv')

In [20]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [32]:
reading = df["Reading_NoInt"].mean()
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [ ]:
df ['meanRT'] = ['Reading_NoInt', '']